// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function CancelTransferTask(arg1:string):Promise<void>;

export function CreateFolder(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteConnection(arg1:string):Promise<void>;

export function DeleteEntry(arg1:string,arg2:string):Promise<void>;

export function DownloadFile(arg1:string,arg2:string,arg3:string,arg4:number):Promise<domain.TransferTask>;

export function ListConnections():Promise<Array<domain.ConnectionProfile>>;

export function ListFiles(arg1:string,arg2:string):Promise<Array<domain.RemoteEntry>>;

export function ListTransferTasks():Promise<Array<domain.TransferTask>>;

export function PickDownloadDirectory():Promise<string>;

export function PickUploadFiles():Promise<Array<string>>;

export function RenameEntry(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SaveConnection(arg1:domain.ConnectionInput):Promise<domain.ConnectionProfile>;

export function TestConnection(arg1:domain.ConnectionInput):Promise<void>;

export function UploadFiles(arg1:string,arg2:string,arg3:Array<string>):Promise<Array<domain.TransferTask>>;
