// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelTransferTask(arg1) {
  return window['go']['main']['App']['CancelTransferTask'](arg1);
}

export function CreateFolder(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateFolder'](arg1, arg2, arg3);
}

export function DeleteConnection(arg1) {
  return window['go']['main']['App']['DeleteConnection'](arg1);
}

export function DeleteEntry(arg1, arg2) {
  return window['go']['main']['App']['DeleteEntry'](arg1, arg2);
}

export function DownloadFile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DownloadFile'](arg1, arg2, arg3, arg4);
}

export function ListConnections() {
  return window['go']['main']['App']['ListConnections']();
}

export function ListFiles(arg1, arg2) {
  return window['go']['main']['App']['ListFiles'](arg1, arg2);
}

export function ListTransferTasks() {
  return window['go']['main']['App']['ListTransferTasks']();
}

export function PathExists(arg1) {
  return window['go']['main']['App']['PathExists'](arg1);
}

export function PickDownloadDirectory() {
  return window['go']['main']['App']['PickDownloadDirectory']();
}

export function PickUploadFiles() {
  return window['go']['main']['App']['PickUploadFiles']();
}

export function RenameEntry(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenameEntry'](arg1, arg2, arg3);
}

export function SaveConnection(arg1) {
  return window['go']['main']['App']['SaveConnection'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}

export function UploadFiles(arg1, arg2, arg3) {
  return window['go']['main']['App']['UploadFiles'](arg1, arg2, arg3);
}
